import Head from "next/head";
import Main from "../components/Main";

import { useState } from "react";

import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

export default function Home() {
  // const [darkMode, setDarkMode] = useState(false);

  return (
    // <div className={darkMode ? "dark" : null}>
    <div>
      <Head>
        <title>Roxana Giba - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Footer />
    </div>
  );
}
